name: Continuous Integration

on:
  pull_request:
    branches: [master, develop]

jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: npm ci
      - run: npm run build
      # - uses: wagoid/commitlint-github-action@v5
